Collections:
- Name: DeepFillv2
  Paper:
    Title: Free-Form Image Inpainting with Gated Convolution
    URL: https://arxiv.org/abs/1806.03589
  README: configs/deepfillv2/README.md
  Task:
  - inpainting
  Year: 2019
Models:
- Config: configs/deepfillv2/deepfillv2_8xb2_celeba-256x256.py
  In Collection: DeepFillv2
  Name: deepfillv2_8xb2_celeba-256x256
  Results:
  - Dataset: CelebA-val
    Metrics:
      PSNR: 25.721
      SSIM: 0.871
      l1 error: 5.411
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/deepfillv2/deepfillv2_256x256_8x2_celeba_20200619-c96e5f12.pth
- Config: configs/deepfillv2/deepfillv2_8xb2_places-256x256.py
  In Collection: DeepFillv2
  Name: deepfillv2_8xb2_places-256x256
  Results:
  - Dataset: Places365-val
    Metrics:
      PSNR: 22.398
      SSIM: 0.815
      l1 error: 8.635
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/deepfillv2/deepfillv2_256x256_8x2_places_20200619-10d15793.pth
