Collections:
- Metadata:
    Architecture:
    - TOFlow
  Name: TOFlow
  Paper:
  - https://arxiv.org/abs/1711.09078
  README: configs/tof/README.md
  Task:
  - video interpolation
  - video super-resolution
  Year: 2019
Models:
- Config: configs/tof/tof_spynet-chair-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-chair-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      PSNR: 33.3294
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_chair_nobn_1xb1_vimeo90k_20220321-2fc9e258.pth
- Config: configs/tof/tof_spynet-kitti-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-kitti-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      PSNR: 33.3339
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_kitti_nobn_1xb1_vimeo90k_20220321-3f7ca4cd.pth
- Config: configs/tof/tof_spynet-sintel-wobn-clean_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-sintel-wobn-clean_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      PSNR: 33.317
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_sintel_clean_nobn_1xb1_vimeo90k_20220321-6e52a6fd.pth
- Config: configs/tof/tof_spynet-sintel-wobn-final_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-sintel-wobn-final_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      PSNR: 33.3237
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_sintel_final_nobn_1xb1_vimeo90k_20220321-8ab70dbb.pth
- Config: configs/tof/tof_spynet-pytoflow-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-pytoflow-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      PSNR: 33.3426
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_pytoflow_nobn_1xb1_vimeo90k_20220321-5f4b243e.pth
- Config: configs/tof/tof_spynet-chair-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-chair-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      SSIM: 0.9465
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_chair_nobn_1xb1_vimeo90k_20220321-2fc9e258.pth
- Config: configs/tof/tof_spynet-kitti-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-kitti-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      SSIM: 0.9466
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_kitti_nobn_1xb1_vimeo90k_20220321-3f7ca4cd.pth
- Config: configs/tof/tof_spynet-sintel-wobn-clean_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-sintel-wobn-clean_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      SSIM: 0.9464
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_sintel_clean_nobn_1xb1_vimeo90k_20220321-6e52a6fd.pth
- Config: configs/tof/tof_spynet-sintel-wobn-final_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-sintel-wobn-final_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      SSIM: 0.9465
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_sintel_final_nobn_1xb1_vimeo90k_20220321-8ab70dbb.pth
- Config: configs/tof/tof_spynet-pytoflow-wobn_1xb1_vimeo90k-triplet.py
  In Collection: TOFlow
  Metadata:
    GPUs: 1 (Tesla PG503-216)
    Training Data: VIMEO90K
  Name: tof_spynet-pytoflow-wobn_1xb1_vimeo90k-triplet
  Results:
  - Dataset: VIMEO90K
    Metrics:
      SSIM: 0.9467
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_pytoflow_nobn_1xb1_vimeo90k_20220321-5f4b243e.pth
- Config: configs/tof/tof_x4_official_vimeo90k.py
  In Collection: TOFlow
  Metadata:
    GPUs: '-'
    Training Data: VIMEO90K
  Name: tof_x4_official_vimeo90k
  Results:
  - Dataset: VIMEO90K
    Metrics:
      Vid4:
        PSNR: 24.4377
        SSIM: 0.7433
    Task: Video Interpolation, Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/tof/tof_x4_vimeo90k_official-a569ff50.pth
