Collections:
- Name: Disco Diffusion
  Paper:
    Title: Disco Diffusion
    URL: https://github.com/alembics/disco-diffusion
  README: configs/disco_diffusion/README.md
  Task:
  - text2image
  - image2image
  Year: 2022
Models:
- Config: configs/disco_diffusion/disco-diffusion_adm-u-finetuned_imagenet-512x512.py
  In Collection: Disco Diffusion
  Name: disco-diffusion_adm-u-finetuned_imagenet-512x512
  Results:
  - Dataset: ImageNet
    Metrics: {}
    Task: Text2Image
  Weights: https://download.openmmlab.com/mmediting/synthesizers/disco/adm-u_finetuned_imagenet-512x512-ab471d70.pth
- Config: configs/disco_diffusion/disco-diffusion_adm-u-finetuned_imagenet-256x256.py
  In Collection: Disco Diffusion
  Name: disco-diffusion_adm-u-finetuned_imagenet-256x256
  Results:
  - Dataset: ImageNet
    Metrics: {}
    Task: Text2Image
  Weights: <>
- Config: configs/disco_diffusion/disco-diffusion_portrait-generator-v001.py
  In Collection: Disco Diffusion
  Name: disco-diffusion_portrait-generator-v001
  Results:
  - Dataset: unknown
    Metrics: {}
    Task: Text2Image
  Weights: https://download.openmmlab.com/mmediting/synthesizers/disco/adm-u-cvt-rgb_portrait-v001-f4a3f3bc.pth
