blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/open-mmlab/mmagic/discussions
    about: Ask general usage questions and discuss with other MMagic community members
  - name: ğŸŒ Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get to know more about OpenMMLab
