Collections:
- Metadata:
    Architecture:
    - BasicVSR
  Name: BasicVSR
  Paper:
  - https://arxiv.org/abs/2012.02181
  README: configs/basicvsr/README.md
  Task:
  - video super-resolution
  Year: 2021
Models:
- Config: configs/basicvsr/basicvsr_2xb4_reds4.py
  In Collection: BasicVSR
  Metadata:
    GPUs: 2 (Tesla V100-PCIE-32GB)
    Training Data: REDS
  Name: basicvsr_2xb4_reds4
  Results:
  - Dataset: REDS
    Metrics:
      REDS4 (BIx4) PSNR (RGB): 31.417
      REDS4 (BIx4) SSIM (RGB): 0.8909
      UDM10 (BDx4) PSNR (Y): 33.4478
      UDM10 (BDx4) SSIM (Y): 0.9306
      Vid4 (BDx4) PSNR (Y): 24.4541
      Vid4 (BDx4) SSIM (Y): 0.7455
      Vid4 (BIx4) PSNR (Y): 27.2694
      Vid4 (BIx4) SSIM (Y): 0.8318
      Vimeo-90K-T (BDx4) PSNR (Y): 34.47
      Vimeo-90K-T (BDx4) SSIM (Y): 0.9286
      Vimeo-90K-T (BIx4) PSNR (Y): 36.2848
      Vimeo-90K-T (BIx4) SSIM (Y): 0.9395
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth
- Config: configs/basicvsr/basicvsr_2xb4_vimeo90k-bi.py
  In Collection: BasicVSR
  Metadata:
    GPUs: 2 (Tesla V100-PCIE-32GB)
    Training Data: VIMEO90K
  Name: basicvsr_2xb4_vimeo90k-bi
  Results:
  - Dataset: VIMEO90K
    Metrics:
      REDS4 (BIx4) PSNR (RGB): 30.3128
      REDS4 (BIx4) SSIM (RGB): 0.866
      UDM10 (BDx4) PSNR (Y): 34.5554
      UDM10 (BDx4) SSIM (Y): 0.9434
      Vid4 (BDx4) PSNR (Y): 25.0517
      Vid4 (BDx4) SSIM (Y): 0.7636
      Vid4 (BIx4) PSNR (Y): 27.2755
      Vid4 (BIx4) SSIM (Y): 0.8248
      Vimeo-90K-T (BDx4) PSNR (Y): 34.8097
      Vimeo-90K-T (BDx4) SSIM (Y): 0.9316
      Vimeo-90K-T (BIx4) PSNR (Y): 37.2026
      Vimeo-90K-T (BIx4) SSIM (Y): 0.9451
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_vimeo90k_bi_20210409-d2d8f760.pth
- Config: configs/basicvsr/basicvsr_2xb4_vimeo90k-bd.py
  In Collection: BasicVSR
  Metadata:
    GPUs: 2 (Tesla V100-PCIE-32GB)
    Training Data: VIMEO90K
  Name: basicvsr_2xb4_vimeo90k-bd
  Results:
  - Dataset: VIMEO90K
    Metrics:
      REDS4 (BIx4) PSNR (RGB): 29.0376
      REDS4 (BIx4) SSIM (RGB): 0.8481
      UDM10 (BDx4) PSNR (Y): 39.9953
      UDM10 (BDx4) SSIM (Y): 0.9695
      Vid4 (BDx4) PSNR (Y): 27.9791
      Vid4 (BDx4) SSIM (Y): 0.8556
      Vid4 (BIx4) PSNR (Y): 26.2708
      Vid4 (BIx4) SSIM (Y): 0.8022
      Vimeo-90K-T (BDx4) PSNR (Y): 37.5501
      Vimeo-90K-T (BDx4) SSIM (Y): 0.9499
      Vimeo-90K-T (BIx4) PSNR (Y): 34.6427
      Vimeo-90K-T (BIx4) SSIM (Y): 0.9335
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_vimeo90k_bd_20210409-0154dd64.pth
