Collections:
- Metadata:
    Architecture:
    - DeepFillv1
  Name: DeepFillv1
  Paper:
  - https://arxiv.org/abs/1801.07892
  README: configs/deepfillv1/README.md
  Task:
  - inpainting
  Year: 2018
Models:
- Config: configs/deepfillv1/deepfillv1_8xb2_places-256x256.py
  In Collection: DeepFillv1
  Metadata:
    GPUs: '8'
    Training Data: PLACES
  Name: deepfillv1_8xb2_places-256x256
  Results:
  - Dataset: PLACES
    Metrics:
      PSNR: 23.429
      SSIM: 0.862
      l1 error: 11.019
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/deepfillv1/deepfillv1_256x256_8x2_places_20200619-c00a0e21.pth
- Config: configs/deepfillv1/deepfillv1_4xb4_celeba-256x256.py
  In Collection: DeepFillv1
  Metadata:
    GPUs: '4'
    Training Data: CELEBA
  Name: deepfillv1_4xb4_celeba-256x256
  Results:
  - Dataset: CELEBA
    Metrics:
      PSNR: 26.878
      SSIM: 0.911
      l1 error: 6.677
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/deepfillv1/deepfillv1_256x256_4x4_celeba_20200619-dd51a855.pth
