Collections:
- Metadata:
    Architecture:
    - SinGAN
  Name: SinGAN
  Paper:
  - https://openaccess.thecvf.com/content_ICCV_2019/html/Shaham_SinGAN_Learning_a_Generative_Model_From_a_Single_Natural_Image_ICCV_2019_paper.html
  README: configs/singan/README.md
  Task:
  - internal learning
  Year: 2019
Models:
- Config: configs/singan/singan_balloons.py
  In Collection: SinGAN
  Metadata:
    Training Data: Others
  Name: singan_balloons
  Results:
  - Dataset: Others
    Metrics:
      Num Scales: 8.0
    Task: Internal Learning
  Weights: https://download.openmmlab.com/mmediting/singan/singan_balloons_20210406_191047-8fcd94cf.pth
- Config: configs/singan/singan_fish.py
  In Collection: SinGAN
  Metadata:
    Training Data: Others
  Name: singan_fish
  Results:
  - Dataset: Others
    Metrics:
      Num Scales: 10.0
    Task: Internal Learning
  Weights: https://download.openmmlab.com/mmediting/singan/singan_fis_20210406_201006-860d91b6.pth
- Config: configs/singan/singan_bohemian.py
  In Collection: SinGAN
  Metadata:
    Training Data: Others
  Name: singan_bohemian
  Results:
  - Dataset: Others
    Metrics:
      Num Scales: 10.0
    Task: Internal Learning
  Weights: https://download.openmmlab.com/mmediting/singan/singan_bohemian_20210406_175439-f964ee38.pth
