Collections:
- Name: PGGAN
  Paper:
    Title: Progressive Growing of GANs for Improved Quality, Stability, and Variation
    URL: https://arxiv.org/abs/1710.10196
  README: configs/pggan/README.md
  Task:
  - unconditional gans
  Year: 2018
Models:
- Config: configs/pggan/pggan_8xb4-12Mimgs_celeba-cropped-128x128.py
  In Collection: PGGAN
  Name: pggan_8xb4-12Mimgs_celeba-cropped-128x128
  Results:
  - Dataset: celeba-cropped
    Metrics:
      MS-SSIM: 0.3023
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/pggan/pggan_celeba-cropped_128_g8_20210408_181931-85a2e72c.pth
- Config: configs/pggan/pggan_8xb4-12Mimgs_lsun-bedroom-128x128.py
  In Collection: PGGAN
  Name: pggan_8xb4-12Mimgs_lsun-bedroom-128x128
  Results:
  - Dataset: lsun-bedroom
    Metrics:
      MS-SSIM: 0.0602
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/pggan/pggan_lsun-bedroom_128x128_g8_20210408_182033-5e59f45d.pth
- Config: configs/pggan/pggan_8xb4-12Mimg_celeba-hq-1024x1024.py
  In Collection: PGGAN
  Name: pggan_8xb4-12Mimg_celeba-hq-1024x1024
  Results:
  - Dataset: celeba-hq
    Metrics:
      MS-SSIM: 0.3379
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/pggan/pggan_celeba-hq_1024_g8_20210408_181911-f1ef51c3.pth
