exclude: ^tests/data/
repos:
  - repo: https://gitee.com/openmmlab/mirrors-flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://gitee.com/openmmlab/mirrors-isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://gitee.com/openmmlab/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://gitee.com/openmmlab/mirrors-pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://gitee.com/openmmlab/mirrors-codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://gitee.com/openmmlab/mirrors-mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
  - repo: https://gitee.com/openmmlab/mirrors-docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://gitee.com/openmmlab/pre-commit-hooks
    rev: v0.2.0  # Use the ref you want to point at
    hooks:
      - id: check-copyright
        args: ["mmcv", "tests", "--excludes", "mmcv/ops"]
  - repo: https://gitee.com/openmmlab/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: |-
          (?x)(
              ^test
              | ^docs
          )
  # - repo: local
  #   #   hooks:
  #     #     - id: clang-format
  #       #       name: clang-format
  #         #       description: Format files with ClangFormat
  #           #       entry: clang-format -style=google -i
  #             #       language: system
  #               #       files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
