Collections:
- Metadata:
    Architecture:
    - PConv
  Name: PConv
  Paper:
  - https://arxiv.org/abs/1804.07723
  README: configs/partial_conv/README.md
  Task:
  - inpainting
  Year: 2018
Models:
- Config: configs/partial_conv/pconv_stage1_8xb12_places-256x256.py
  In Collection: PConv
  Metadata:
    GPUs: '8'
    Training Data: PLACES
  Name: pconv_stage1_8xb12_places-256x256
  Results:
  - Dataset: PLACES
    Metrics: {}
    Task: Inpainting
  Weights: ''
- Config: configs/partial_conv/pconv_stage2_4xb2_places-256x256.py
  In Collection: PConv
  Metadata:
    GPUs: '4'
    Training Data: PLACES
  Name: pconv_stage2_4xb2_places-256x256
  Results:
  - Dataset: PLACES
    Metrics:
      PSNR: 22.762
      SSIM: 0.801
      l1 error: 8.776
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/pconv/pconv_256x256_stage2_4x2_places_20200619-1ffed0e8.pth
- Config: configs/partial_conv/pconv_stage1_8xb1_celeba-256x256.py
  In Collection: PConv
  Metadata:
    GPUs: '8'
    Training Data: CELEBA
  Name: pconv_stage1_8xb1_celeba-256x256
  Results:
  - Dataset: CELEBA
    Metrics: {}
    Task: Inpainting
  Weights: ''
- Config: configs/partial_conv/pconv_stage2_4xb2_celeba-256x256.py
  In Collection: PConv
  Metadata:
    GPUs: '4'
    Training Data: CELEBA
  Name: pconv_stage2_4xb2_celeba-256x256
  Results:
  - Dataset: CELEBA
    Metrics:
      PSNR: 25.404
      SSIM: 0.853
      l1 error: 5.99
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/pconv/pconv_256x256_stage2_4x2_celeba_20200619-860f8b95.pth
