Collections:
- Metadata:
    Architecture:
    - SRGAN
  Name: SRGAN
  Paper:
  - https://arxiv.org/abs/1609.04802
  README: configs/srgan_resnet/README.md
  Task:
  - image super-resolution
  Year: 2016
Models:
- Config: configs/srgan_resnet/msrresnet_x4c64b16_1xb16-1000k_div2k.py
  In Collection: SRGAN
  Metadata:
    GPUs: '1'
    Training Data: DIV2K
  Name: msrresnet_x4c64b16_1xb16-1000k_div2k
  Results:
  - Dataset: DIV2K
    Metrics:
      DIV2K PSNR: 28.9748
      DIV2K SSIM: 0.8178
      Set14 PSNR: 26.7762
      Set14 SSIM: 0.7369
      Set5 PSNR: 30.2252
      Set5 SSIM: 0.8491
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/srresnet_srgan/msrresnet_x4c64b16_1x16_300k_div2k_20200521-61556be5.pth
- Config: configs/srgan_resnet/srgan_x4c64b16_1xb16-1000k_div2k.py
  In Collection: SRGAN
  Metadata:
    GPUs: '1'
    Training Data: DIV2K
  Name: srgan_x4c64b16_1xb16-1000k_div2k
  Results:
  - Dataset: DIV2K
    Metrics:
      DIV2K PSNR: 26.5697
      DIV2K SSIM: 0.7365
      Set14 PSNR: 24.7383
      Set14 SSIM: 0.6491
      Set5 PSNR: 27.9499
      Set5 SSIM: 0.7846
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/srresnet_srgan/srgan_x4c64b16_1x16_1000k_div2k_20200606-a1f0810e.pth
