Collections:
- Metadata:
    Architecture:
    - Pix2Pix
  Name: Pix2Pix
  Paper:
  - https://openaccess.thecvf.com/content_cvpr_2017/html/Isola_Image-To-Image_Translation_With_CVPR_2017_paper.html
  README: configs/pix2pix/README.md
  Task:
  - image2image
  Year: 2017
Models:
- Config: configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-80kiters_facades.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: FACADES
  Name: pix2pix_vanilla-unet-bn_1xb1-80kiters_facades
  Results:
  - Dataset: FACADES
    Metrics:
      FID: 124.9773
      IS: 1.62
    Task: Image2Image
  Weights: https://download.openmmlab.com/mmediting/pix2pix/refactor/pix2pix_vanilla_unet_bn_1x1_80k_facades_20210902_170442-c0958d50.pth
- Config: configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_aerial2maps.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: MAPS
  Name: pix2pix_vanilla-unet-bn_1xb1-220kiters_aerial2maps
  Results:
  - Dataset: MAPS
    Metrics:
      FID: 122.5856
      IS: 3.137
    Task: Image2Image
  Weights: https://download.openmmlab.com/mmediting/pix2pix/refactor/pix2pix_vanilla_unet_bn_a2b_1x1_219200_maps_convert-bgr_20210902_170729-59a31517.pth
- Config: configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_maps2aerial.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: MAPS
  Name: pix2pix_vanilla-unet-bn_1xb1-220kiters_maps2aerial
  Results:
  - Dataset: MAPS
    Metrics:
      FID: 88.4635
      IS: 3.31
    Task: Image2Image
  Weights: https://download.openmmlab.com/mmediting/pix2pix/refactor/pix2pix_vanilla_unet_bn_b2a_1x1_219200_maps_convert-bgr_20210902_170814-6d2eac4a.pth
- Config: configs/pix2pix/pix2pix_vanilla-unet-bn_wo-jitter-flip-1xb4-190kiters_edges2shoes.py
  In Collection: Pix2Pix
  Metadata:
    Training Data: EDGES2SHOES
  Name: pix2pix_vanilla-unet-bn_wo-jitter-flip-1xb4-190kiters_edges2shoes
  Results:
  - Dataset: EDGES2SHOES
    Metrics:
      FID: 84.375
      IS: 2.815
    Task: Image2Image
  Weights: https://download.openmmlab.com/mmediting/pix2pix/refactor/pix2pix_vanilla_unet_bn_wo_jitter_flip_1x4_186840_edges2shoes_convert-bgr_20210902_170902-0c828552.pth
