Collections:
- Metadata:
    Architecture:
    - ESRGAN
  Name: ESRGAN
  Paper:
  - https://arxiv.org/abs/1809.00219
  README: configs/esrgan/README.md
  Task:
  - image super-resolution
  Year: 2018
Models:
- Config: configs/esrgan/esrgan_psnr-x4c64b23g32_1xb16-1000k_div2k.py
  In Collection: ESRGAN
  Metadata:
    GPUs: '1'
    Training Data: DIV2K
  Name: esrgan_psnr-x4c64b23g32_1xb16-1000k_div2k
  Results:
  - Dataset: DIV2K
    Metrics:
      DIV2K PSNR: 29.3354
      DIV2K SSIM: 0.8263
      Set14 PSNR: 27.0543
      Set14 SSIM: 0.7447
      Set5 PSNR: 30.6428
      Set5 SSIM: 0.8559
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/esrgan/esrgan_psnr_x4c64b23g32_1x16_1000k_div2k_20200420-bf5c993c.pth
- Config: configs/esrgan/esrgan_x4c64b23g32_1xb16-400k_div2k.py
  In Collection: ESRGAN
  Metadata:
    GPUs: '1'
    Training Data: DIV2K
  Name: esrgan_x4c64b23g32_1xb16-400k_div2k
  Results:
  - Dataset: DIV2K
    Metrics:
      DIV2K PSNR: 26.6531
      DIV2K SSIM: 0.734
      Set14 PSNR: 24.6328
      Set14 SSIM: 0.6491
      Set5 PSNR: 28.27
      Set5 SSIM: 0.7778
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/esrgan/esrgan_x4c64b23g32_1x16_400k_div2k_20200508-f8ccaf3b.pth
